name: Dispatch Commenter

on:
  repository_dispatch:
    types:
      - test-coverage-ready

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.client_payload.pr_number }}
      SHA: ${{ github.event.client_payload.sha }}
    steps:
     - name: Print info
       run: |
        echo "Your PR is ${PR_NUMBER}, SHA is ${SHA}"
     - name: Checkout
       uses: actions/checkout@v4
       with:
        ref: ${{ env.SHA }}
     - name: Download file
       run: |
         curl -q -o file.json https://file-examples.com/storage/fe6a71582967c9a269c25cd/2017/02/file_example_JSON_1kb.json
     - name: Build report
       run: |
         echo "File length is `wc -l file.json` lines" > report.out
     - name: Print report
       run: |
        cat report.out
     - name: Add comment to PR
       uses: marocchino/sticky-pull-request-comment@v2
       with:
         header: test-coverage
         number: ${{ env.PR_NUMBER }}
         message: |
           Requested comment for commit with ${{ env.SHA }}
