name: Upload coverage to master

# POST https://api.github.com/repos/cronfy/github-repository-dispatch-pr-comment/dispatches
# Authorization: token ...
# Content-Type: application/json
# Accept: application/vnd.github.everest-preview+json
#
# {
#   "event_type":  "master-coverage-ready",
#   "client_payload": {
#     "buildkite_build_number": "123321"
#     "build_sha": "5de6ee8cd2d9a4927cd11124c33a6aa7e985ab64"
#   }
# }

on:
  repository_dispatch:
    types:
      - master-coverage-ready

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDKITE_BUILD_NUMBER: ${{ github.event.client_payload.buildkite_build_number }}
      BUILD_SHA: ${{ github.event.client_payload.build_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Get coverage from buildkite build
        env:
          BUILDKITE_API_TOKEN: ${{ secrets.BUILDKITE_API_TOKEN }}
        run: |
          ./.github/buildkite-download-coverage-artifacts.sh ${{ env.BUILDKITE_BUILD_NUMBER }} ./buildkite-coverage 

      - name: Upload buildkite coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildkite-coverage-${{ env.BUILD_SHA }}
          path: buildkite-coverage/

      - uses: actions/setup-go@v5

      - name: Merge coverage
        run: |
          go install github.com/wadey/gocovmerge@b5bfa59ec0adc420475f97f89b58045c721d761c
          gocovmerge ./buildkite-coverage/*.coverage.out > coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ env.BUILD_SHA }}
          path: coverage.out
