name: Dispatch Commenter

on:
  repository_dispatch:
    types:
      - test-coverage-ready

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch trigger
        run: |
          echo "repository_dispatch triggered"
