name: Dispatch Commenter

on:
  repository_dispatch:
    types:
      - test-coverage-ready

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.client_payload.pr_number }}
      SHA: ${{ github.event.client_payload.sha }}
    steps:
     - name: Print info
       run: |
        echo "Your PR is ${PR}, SHA is ${SHA}"
     - name: Checkout
       uses: actions/checkout@v4
       with:
        ref: ${SHA}
     - name: List files
       run: |
        ls
